version: "2.0"
name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build \
            --pull \
            --cache-from chisty/real-estate-restaurant:latest \
            --tag chisty/real-estate-restaurant:latest \
            --file Dockerfile .
      - name: Push Docker image to Docker Hub
        run: docker push chisty/real-estate-restaurant:latest
